### ISSUE TITLE
Adopt payjoin.org 2.0 design revamp

### ISSUE THREAD

**Issue by DanGould** [payjoin/payjoin.org#15]
@thebrandonlucas has been putting in hard work here already https://github.com/thebrandonlucas/payjoin.github.io

designs: https://www.figma.com/file/WTqXA6ykLOYEyo2N3wfCGZ/payjoin-%F0%9F%94%97-Design-(Copy)?type=design&node-id=28%3A4&mode=design&t=d0yCECPs5fGVfWo6-1

side note: Bitcoin Design seems to be moving to OSS PenPot. Wonder if we [sh/c]ould too.

**Comment by thebrandonlucas** [comment]
+1 for PenPot, I can investigate porting things over. I figure if it's good enough for Bitcoin Design it's good enough for us!
