### ISSUE TITLE
Remove horizontal scroll bar

### ISSUE THREAD

**Issue by DanGould** [payjoin/payjoin.org#22]
nobody needs to scroll 6 px left to right

**Comment by thebrandonlucas** [comment]
@DanGould What browser(s) is this happening on for you?

**Comment by DanGould** [comment]
FF & Chrome

Chrome:

<img width="1440" alt="image" src="https://github.com/payjoin/payjoin.org/assets/8525467/041bd342-48bd-46f0-b145-4f4faa538fa8">

**Comment by DanGould** [comment]
This is happening again and might be related to the nav

**Comment by thebrandonlucas** [comment]
Closing this as it no longer appears to be an issue
