### ISSUE TITLE
Add Introduction Article

### ISSUE THREAD

**Issue by thebrandonlucas** [payjoin/payjoin.org#64]
During the [migration to docusaurus](https://github.com/payjoin/payjoin.org/pull/63), we decided to exclude rough draft articles to explain payjoin, v1, v2, and `payjoin-cli` to limit the scope of the switchover.

This issue is to merge the introductory article so people have a natural, in-site way to learn more about payjoin.

**Comment by DanGould** [comment]
closed by #69
